
rt java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
  * To change this template file, choose Tools | Templates
   * and open the template in the editor.
    */
    /**
     *
      * @author guleid
       */
       public class LogIn extends javax.swing.JFrame {

           /**
	        * Creates new form LogIn
		     */
		       
		           Connection conn = null;
			       PreparedStatement pst = null; //Sending SQL statement to database 
			           ResultSet rs = null; //Represents database result set 
				       
				           public LogIn() {
					           DBConnect db = new DBConnect();
						           
							          // db.connect();
								          initComponents();
									          
										      }
										          /**
											       * This method is called from within the constructor to initialize the form.
											            * WARNING: Do NOT modify this code. The content of this method is always
												         * regenerated by the Form Editor.
													      */
													          @SuppressWarnings("unchecked")
														      // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
														          private void initComponents() {

															          jPanel1 = new javax.swing.JPanel();
																          jLabel1 = new javax.swing.JLabel();
																	          txt_username = new javax.swing.JTextField();
																		          jLabel2 = new javax.swing.JLabel();
																			          jButton1 = new javax.swing.JButton();
																				          jButton2 = new javax.swing.JButton();
																					          txt_password = new javax.swing.JPasswordField();

																						          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
																							          addWindowListener(new java.awt.event.WindowAdapter() {
																								              public void windowOpened(java.awt.event.WindowEvent evt) {
																									                      formWindowOpened(evt);
																											                  }
																													          });

																														          jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 51, 204))); // NOI18N

																															          jLabel1.setText("Username:");

																																          jLabel2.setText("Password:");

																																	          jButton1.setText("Log In");
																																		          jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
																																			              public void mouseClicked(java.awt.event.MouseEvent evt) {
																																				                      jButton1MouseClicked(evt);
																																						                  }
																																								          });
																																									          jButton1.addActionListener(new java.awt.event.ActionListener() {
																																										              public void actionPerformed(java.awt.event.ActionEvent evt) {
																																											                      jButton1ActionPerformed(evt);
																																													                  }
																																															          });

																																																          jButton2.setText("Register");
																																																	          jButton2.addActionListener(new java.awt.event.ActionListener() {
																																																		              public void actionPerformed(java.awt.event.ActionEvent evt) {
																																																			                      jButton2ActionPerformed(evt);
																																																					                  }
																																																							          });

																																																								          txt_password.addActionListener(new java.awt.event.ActionListener() {
																																																									              public void actionPerformed(java.awt.event.ActionEvent evt) {
																																																										                      txt_passwordActionPerformed(evt);
																																																												                  }
																																																														          });

																																																															          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
																																																																          jPanel1.setLayout(jPanel1Layout);
																																																																	          jPanel1Layout.setHorizontalGroup(
																																																																		              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																																																			                  .addGroup(jPanel1Layout.createSequentialGroup()
																																																																					                  .addContainerGap()
																																																																							                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																																																									                      .addComponent(jLabel1)
																																																																											                          .addComponent(jLabel2))
																																																																														                  .addGap(45, 45, 45)
																																																																																                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																																																																																		                      .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
																																																																																				                          .addComponent(txt_password))
																																																																																							                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																																																																																									              .addGroup(jPanel1Layout.createSequentialGroup()
																																																																																										                      .addGap(29, 29, 29)
																																																																																												                      .addComponent(jButton1)
																																																																																														                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
																																																																																																                      .addComponent(jButton2)
																																																																																																		                      .addGap(71, 71, 71))
																																																																																																				              );
																																																																																																					              jPanel1Layout.setVerticalGroup(
																																																																																																						                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																																																																																								              .addGroup(jPanel1Layout.createSequentialGroup()
																																																																																																									                      .addContainerGap()
																																																																																																											                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																																																																																																													                          .addComponent(jLabel1)
																																																																																																																                      .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
																																																																																																																		                      .addGap(28, 28, 28)
																																																																																																																				                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																																																																																																																						                          .addComponent(jLabel2)
																																																																																																																									                      .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																																																																																																																											                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
																																																																																																																													                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																																																																																																																															                          .addComponent(jButton1)
																																																																																																																																		                      .addComponent(jButton2))
																																																																																																																																				                      .addGap(50, 50, 50))
																																																																																																																																						              );

																																																																																																																																							              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
																																																																																																																																								              getContentPane().setLayout(layout);
																																																																																																																																									              layout.setHorizontalGroup(
																																																																																																																																										                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																																																																																																																												              .addGroup(layout.createSequentialGroup()
																																																																																																																																													                      .addGap(220, 220, 220)
																																																																																																																																															                      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																																																																																																																																																	                      .addContainerGap(271, Short.MAX_VALUE))
																																																																																																																																																			              );
																																																																																																																																																				              layout.setVerticalGroup(
																																																																																																																																																					                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																																																																																																																																							              .addGroup(layout.createSequentialGroup()
																																																																																																																																																								                      .addGap(171, 171, 171)
																																																																																																																																																										                      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																																																																																																																																																												                      .addContainerGap(250, Short.MAX_VALUE))
																																																																																																																																																														              );

																																																																																																																																																															              pack();
																																																																																																																																																																          }// </editor-fold>                        

																																																																																																																																																																	      private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
																																																																																																																																																																	              // TODO add your handling code here:    
																																																																																																																																																																		              
																																																																																																																																																																			              String sql = "select * from user where username=? and userPassword=?";
																																																																																																																																																																				              try {
																																																																																																																																																																					                  pst = conn.prepareStatement(sql);
																																																																																																																																																																							              pst.setString(1, txt_username.getText()); //Retrieving username from database
																																																																																																																																																																								                  pst.setString(2, txt_password.getText()); //Retrieving password from database 
																																																																																																																																																																										              rs = pst.executeQuery(); 
																																																																																																																																																																											                  if (rs.next()) {
																																																																																																																																																																													                  JOptionPane.showMessageDialog(null, "Successful Authentication");
																																																																																																																																																																															                  dispose();
																																																																																																																																																																																	                  Welcome w = new Welcome(); //Calls the Welcome class
																																																																																																																																																																																			                  w.setVisible(true); //Opens the Welcome frame 
																																																																																																																																																																																					                  
																																																																																																																																																																																							              }
																																																																																																																																																																																								                  else{
																																																																																																																																																																																										                  JOptionPane.showMessageDialog(null, "Incorrect username or password"); 
																																																																																																																																																																																												              }
																																																																																																																																																																																													              }catch(Exception e){
																																																																																																																																																																																														                  
																																																																																																																																																																																																          }
																																																																																																																																																																																																	          
																																																																																																																																																																																																		      }                                        

																																																																																																																																																																																																		          private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
																																																																																																																																																																																																			          // TODO add your handling code here:
																																																																																																																																																																																																				          Register rgs = new Register();
																																																																																																																																																																																																					          rgs.setVisible(true); //Shows the register form after being clicked
																																																																																																																																																																																																						          dispose();
																																																																																																																																																																																																							           
																																																																																																																																																																																																								       }                                        

																																																																																																																																																																																																								           private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {                                             
																																																																																																																																																																																																									           // TODO add your handling code here:
																																																																																																																																																																																																										       }                                            

																																																																																																																																																																																																										           private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
																																																																																																																																																																																																											           // TODO add your handling code here:
																																																																																																																																																																																																												           conn = DBConnect.connectDB();
																																																																																																																																																																																																													       }                                 

																																																																																																																																																																																																													           private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
																																																																																																																																																																																																														           // TODO add your handling code here:
																																																																																																																																																																																																															       
																																																																																																																																																																																																															               
																																																																																																																																																																																																																           }                                     

																																																																																																																																																																																																																	       /**
																																																																																																																																																																																																																	            * @param args the command line arguments
																																																																																																																																																																																																																		         */
																																																																																																																																																																																																																			     public static void main(String args[]) {
																																																																																																																																																																																																																			             /* Set the Nimbus look and feel */
																																																																																																																																																																																																																				             //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
																																																																																																																																																																																																																					             /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
																																																																																																																																																																																																																						              * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
																																																																																																																																																																																																																							               */
																																																																																																																																																																																																																								               try {
																																																																																																																																																																																																																									                   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
																																																																																																																																																																																																																											                   if ("Nimbus".equals(info.getName())) {
																																																																																																																																																																																																																													                       javax.swing.UIManager.setLookAndFeel(info.getClassName());
																																																																																																																																																																																																																															                           break;
																																																																																																																																																																																																																																		                   }
																																																																																																																																																																																																																																				               }
																																																																																																																																																																																																																																					               } catch (ClassNotFoundException ex) {
																																																																																																																																																																																																																																						                   java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
																																																																																																																																																																																																																																								           } catch (InstantiationException ex) {
																																																																																																																																																																																																																																									               java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
																																																																																																																																																																																																																																										               } catch (IllegalAccessException ex) {
																																																																																																																																																																																																																																											                   java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
																																																																																																																																																																																																																																													           } catch (javax.swing.UnsupportedLookAndFeelException ex) {
																																																																																																																																																																																																																																														               java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
																																																																																																																																																																																																																																															               }
																																																																																																																																																																																																																																																               //</editor-fold>

																																																																																																																																																																																																																																																	               /* Create and display the form */
																																																																																																																																																																																																																																																		               java.awt.EventQueue.invokeLater(new Runnable() {
																																																																																																																																																																																																																																																			                   public void run() {
																																																																																																																																																																																																																																																					                   new LogIn().setVisible(true);
																																																																																																																																																																																																																																																							               }
																																																																																																																																																																																																																																																								               });
																																																																																																																																																																																																																																																									           }

																																																																																																																																																																																																																																																										       // Variables declaration - do not modify                     
																																																																																																																																																																																																																																																										           private javax.swing.JButton jButton1;
																																																																																																																																																																																																																																																											       private javax.swing.JButton jButton2;
																																																																																																																																																																																																																																																											           private javax.swing.JLabel jLabel1;
																																																																																																																																																																																																																																																												       private javax.swing.JLabel jLabel2;
																																																																																																																																																																																																																																																												           private javax.swing.JPanel jPanel1;
																																																																																																																																																																																																																																																													       private javax.swing.JPasswordField txt_password;
																																																																																																																																																																																																																																																													           private javax.swing.JTextField txt_username;
																																																																																																																																																																																																																																																														       / End of variables declaration                   
																																																																																																																																																																																																																																																														       }
